# Generated by Django 4.2 on 2023-04-30 13:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='تصویر')),
                ('discription', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن درباره ما')),
            ],
        ),
    ]
