# Generated by Django 4.2 on 2023-04-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutUs',
        ),
    ]
