# Generated by Django 4.2 on 2023-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_about_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='تصویر'),
        ),
    ]
