# Generated by Django 4.2 on 2023-05-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutus_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'درباره ما'},
        ),
    ]
