# Generated by Django 4.2 on 2023-05-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
    ]
