# Generated by Django 4.2 on 2023-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_photo_title_alter_photo_category_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
