# Generated by Django 4.2 on 2023-05-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی نمونه کار ها', 'verbose_name_plural': 'دسته بندی نمونه کار ها'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کار'},
        ),
    ]
