# Generated by Django 4.2 on 2023-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('banner', models.ImageField(null=True, upload_to='', verbose_name='تصویر')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='تاریخ_ایجاد')),
                ('view', models.PositiveBigIntegerField(default=0, verbose_name='بازدید')),
            ],
        ),
    ]
