# Generated by Django 4.2 on 2023-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_category_delete_articles_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='article',
            name='meta_descreption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_Descreption'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_title'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='اسلاگ'),
        ),
    ]
