# Generated by Django 4.2 on 2023-05-03 10:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_article_meta_descreption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='discription',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='متن مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='short_discription',
            field=models.TextField(max_length=2000, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر شاخس'),
        ),
    ]
