# Generated by Django 4.2 on 2023-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='banner',
        ),
        migrations.AddField(
            model_name='article',
            name='one_banner',
            field=models.ImageField(default=1, upload_to='', verbose_name='تصویر اول مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tree_banner',
            field=models.ImageField(default=1, upload_to='', verbose_name='تصویر سوم مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='two_banner',
            field=models.ImageField(default=2, upload_to='', verbose_name='تصویر دوم مقاله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='یک "Slug" معتبر متشکل از حروف، اعداد، زیرخط یا خط فاصله وارد کنید. ', null=True, verbose_name='اسلاگ'),
        ),
    ]
