# Generated by Django 4.2 on 2023-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_banner_article_one_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_discription',
            field=models.TextField(max_length=70, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
