# Generated by Django 4.2 on 2023-05-03 14:06

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_short_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ_ایجاد'),
        ),
    ]
