# Generated by Django 4.2 on 2023-05-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='blog.article', verbose_name='مقالات مرتبط'),
        ),
    ]
