# Generated by Django 4.2 on 2023-05-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_article_related_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی مقالات', 'verbose_name_plural': 'دسته بندی مقالات'},
        ),
    ]
