# Generated by Django 4.2 on 2023-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_discription',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
