# Generated by Django 4.2 on 2023-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_short_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='یک اسلاگ معتبر متشکل از حروف، اعداد، زیرخط یا خط فاصله وارد کنید. ', null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
