# Generated by Django 4.2 on 2023-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='view',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
