# Generated by Django 4.2 on 2023-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_article_view_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
