# Generated by Django 4.2 on 2023-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_article_views_article_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, help_text='یک اسلاگ معتبر متشکل از حروف، اعداد، زیرخط یا خط فاصله وارد کنید. ', unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
