# Generated by Django 4.2 on 2023-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='یک اسلاگ معتبر متشکل از حروف، اعداد، زیرخط یا خط فاصله وارد کنید. ', verbose_name='اسلاگ'),
        ),
    ]
