# Generated by Django 4.2 on 2023-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='یک اسلاگ معتبر متشکل از حروف، اعداد، زیرخط یا خط فاصله وارد کنید. ', null=True, verbose_name='اسلاگ'),
        ),
    ]
