# Generated by Django 4.2 on 2023-05-07 07:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ_ایجاد'),
        ),
    ]
