# Generated by Django 4.2 on 2023-05-07 08:06

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ_ایجاد'),
        ),
    ]
